### ISSUE TITLE
PyChOpMarg not starting

### ISSUE THREAD

**Issue by dghan0219** [capn-freako/PyChOpMarg#10]
(pychopmarg) C:\>pychopmarg
matplotlib not found while setting up plotting
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dghan\.venv\pychopmarg\Scripts\pychopmarg.exe\__main__.py", line 4, in <module>
  File "C:\Users\dghan\.venv\pychopmarg\Lib\site-packages\pychopmarg\cli.py", line 35, in <module>
    @cli.command(context_settings=dict(help_option_names=["-h", "--help"]))
     ^^^
NameError: name 'cli' is not defined

I installed matplotlib to eliminate the first error, but the others remained.  I'm using Python 3.11.9.

**Comment by capn-freako** [comment]
The GUI is broken.
Jupyter notebook use only, for now.
-db
